<?xml version="1.0" encoding="UTF-8"?><testrun name="TestDataSet" project="cs509_lzhu_hdd" tests="6" started="6" failures="0" errors="1" ignored="0">
  <testsuite name="model.TestDataSet" time="0.077">
    <testcase name="testDeleteDataPointGivenObject" classname="model.TestDataSet" time="0.002"/>
    <testcase name="testDataSetInit" classname="model.TestDataSet" time="0.0"/>
    <testcase name="testDeleteDatePonitGivenIndex" classname="model.TestDataSet" time="0.07">
      <error>java.lang.IndexOutOfBoundsException: Index: 7, Size: 1&#13;
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)&#13;
	at java.util.ArrayList.remove(ArrayList.java:474)&#13;
	at model.DataSet.deleteDataPoint(DataSet.java:58)&#13;
	at model.TestDataSet.testDeleteDatePonitGivenIndex(TestDataSet.java:57)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:606)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:164)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:130)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&#13;
	at junit.framework.TestResult.run(TestResult.java:109)&#13;
	at junit.framework.TestCase.run(TestCase.java:120)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:225)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</error>
    </testcase>
    <testcase name="testEditDataPoint" classname="model.TestDataSet" time="0.001"/>
    <testcase name="testSaveData" classname="model.TestDataSet" time="0.002"/>
    <testcase name="testLoadData" classname="model.TestDataSet" time="0.002"/>
  </testsuite>
</testrun>
