<?xml version="1.0" encoding="UTF-8"?><testrun name="TestDataPoint" project="cs509_lzhu_hdd" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="model.TestDataPoint" time="0.001">
    <testcase name="testDataPointInit" classname="model.TestDataPoint" time="0.0"/>
    <testcase name="testDataPointIsDouble" classname="model.TestDataPoint" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;false&gt; but was:&lt;true&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:47)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:280)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:64)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:146)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:152)&#13;
	at model.TestDataPoint.testDataPointIsDouble(TestDataPoint.java:15)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:606)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:164)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:130)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:106)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:124)&#13;
	at junit.framework.TestResult.run(TestResult.java:109)&#13;
	at junit.framework.TestCase.run(TestCase.java:120)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:230)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:225)&#13;
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
